# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alion/simulation/git/ITEPION/CRu/detector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alion/simulation/git/ITEPION/CRu/detector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alion/simulation/git/ITEPION/CRu/detector/CMakeFiles /home/alion/simulation/git/ITEPION/CRu/detector//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alion/simulation/git/ITEPION/CRu/detector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Mdet

# Build rule for target.
Mdet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Mdet
.PHONY : Mdet

# fast build rule for target.
Mdet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/build
.PHONY : Mdet/fast

Mdet.o: Mdet.cc.o

.PHONY : Mdet.o

# target to build an object file
Mdet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/Mdet.cc.o
.PHONY : Mdet.cc.o

Mdet.i: Mdet.cc.i

.PHONY : Mdet.i

# target to preprocess a source file
Mdet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/Mdet.cc.i
.PHONY : Mdet.cc.i

Mdet.s: Mdet.cc.s

.PHONY : Mdet.s

# target to generate assembly for a file
Mdet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/Mdet.cc.s
.PHONY : Mdet.cc.s

src/Action.o: src/Action.cc.o

.PHONY : src/Action.o

# target to build an object file
src/Action.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Action.cc.o
.PHONY : src/Action.cc.o

src/Action.i: src/Action.cc.i

.PHONY : src/Action.i

# target to preprocess a source file
src/Action.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Action.cc.i
.PHONY : src/Action.cc.i

src/Action.s: src/Action.cc.s

.PHONY : src/Action.s

# target to generate assembly for a file
src/Action.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Action.cc.s
.PHONY : src/Action.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/Functions.o: src/Functions.cc.o

.PHONY : src/Functions.o

# target to build an object file
src/Functions.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Functions.cc.o
.PHONY : src/Functions.cc.o

src/Functions.i: src/Functions.cc.i

.PHONY : src/Functions.i

# target to preprocess a source file
src/Functions.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Functions.cc.i
.PHONY : src/Functions.cc.i

src/Functions.s: src/Functions.cc.s

.PHONY : src/Functions.s

# target to generate assembly for a file
src/Functions.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Functions.cc.s
.PHONY : src/Functions.cc.s

src/Generator.o: src/Generator.cc.o

.PHONY : src/Generator.o

# target to build an object file
src/Generator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Generator.cc.o
.PHONY : src/Generator.cc.o

src/Generator.i: src/Generator.cc.i

.PHONY : src/Generator.i

# target to preprocess a source file
src/Generator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Generator.cc.i
.PHONY : src/Generator.cc.i

src/Generator.s: src/Generator.cc.s

.PHONY : src/Generator.s

# target to generate assembly for a file
src/Generator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Generator.cc.s
.PHONY : src/Generator.cc.s

src/MyParallelWorld.o: src/MyParallelWorld.cc.o

.PHONY : src/MyParallelWorld.o

# target to build an object file
src/MyParallelWorld.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/MyParallelWorld.cc.o
.PHONY : src/MyParallelWorld.cc.o

src/MyParallelWorld.i: src/MyParallelWorld.cc.i

.PHONY : src/MyParallelWorld.i

# target to preprocess a source file
src/MyParallelWorld.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/MyParallelWorld.cc.i
.PHONY : src/MyParallelWorld.cc.i

src/MyParallelWorld.s: src/MyParallelWorld.cc.s

.PHONY : src/MyParallelWorld.s

# target to generate assembly for a file
src/MyParallelWorld.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/MyParallelWorld.cc.s
.PHONY : src/MyParallelWorld.cc.s

src/PrimaryParticles.o: src/PrimaryParticles.cc.o

.PHONY : src/PrimaryParticles.o

# target to build an object file
src/PrimaryParticles.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/PrimaryParticles.cc.o
.PHONY : src/PrimaryParticles.cc.o

src/PrimaryParticles.i: src/PrimaryParticles.cc.i

.PHONY : src/PrimaryParticles.i

# target to preprocess a source file
src/PrimaryParticles.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/PrimaryParticles.cc.i
.PHONY : src/PrimaryParticles.cc.i

src/PrimaryParticles.s: src/PrimaryParticles.cc.s

.PHONY : src/PrimaryParticles.s

# target to generate assembly for a file
src/PrimaryParticles.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/PrimaryParticles.cc.s
.PHONY : src/PrimaryParticles.cc.s

src/RNGWrapper.o: src/RNGWrapper.cc.o

.PHONY : src/RNGWrapper.o

# target to build an object file
src/RNGWrapper.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/RNGWrapper.cc.o
.PHONY : src/RNGWrapper.cc.o

src/RNGWrapper.i: src/RNGWrapper.cc.i

.PHONY : src/RNGWrapper.i

# target to preprocess a source file
src/RNGWrapper.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/RNGWrapper.cc.i
.PHONY : src/RNGWrapper.cc.i

src/RNGWrapper.s: src/RNGWrapper.cc.s

.PHONY : src/RNGWrapper.s

# target to generate assembly for a file
src/RNGWrapper.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/RNGWrapper.cc.s
.PHONY : src/RNGWrapper.cc.s

src/SensitiveDetector.o: src/SensitiveDetector.cc.o

.PHONY : src/SensitiveDetector.o

# target to build an object file
src/SensitiveDetector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/SensitiveDetector.cc.o
.PHONY : src/SensitiveDetector.cc.o

src/SensitiveDetector.i: src/SensitiveDetector.cc.i

.PHONY : src/SensitiveDetector.i

# target to preprocess a source file
src/SensitiveDetector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/SensitiveDetector.cc.i
.PHONY : src/SensitiveDetector.cc.i

src/SensitiveDetector.s: src/SensitiveDetector.cc.s

.PHONY : src/SensitiveDetector.s

# target to generate assembly for a file
src/SensitiveDetector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/SensitiveDetector.cc.s
.PHONY : src/SensitiveDetector.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/Time.o: src/Time.cc.o

.PHONY : src/Time.o

# target to build an object file
src/Time.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Time.cc.o
.PHONY : src/Time.cc.o

src/Time.i: src/Time.cc.i

.PHONY : src/Time.i

# target to preprocess a source file
src/Time.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Time.cc.i
.PHONY : src/Time.cc.i

src/Time.s: src/Time.cc.s

.PHONY : src/Time.s

# target to generate assembly for a file
src/Time.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mdet.dir/build.make CMakeFiles/Mdet.dir/src/Time.cc.s
.PHONY : src/Time.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Mdet"
	@echo "... Mdet.o"
	@echo "... Mdet.i"
	@echo "... Mdet.s"
	@echo "... src/Action.o"
	@echo "... src/Action.i"
	@echo "... src/Action.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/Functions.o"
	@echo "... src/Functions.i"
	@echo "... src/Functions.s"
	@echo "... src/Generator.o"
	@echo "... src/Generator.i"
	@echo "... src/Generator.s"
	@echo "... src/MyParallelWorld.o"
	@echo "... src/MyParallelWorld.i"
	@echo "... src/MyParallelWorld.s"
	@echo "... src/PrimaryParticles.o"
	@echo "... src/PrimaryParticles.i"
	@echo "... src/PrimaryParticles.s"
	@echo "... src/RNGWrapper.o"
	@echo "... src/RNGWrapper.i"
	@echo "... src/RNGWrapper.s"
	@echo "... src/SensitiveDetector.o"
	@echo "... src/SensitiveDetector.i"
	@echo "... src/SensitiveDetector.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/Time.o"
	@echo "... src/Time.i"
	@echo "... src/Time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

